### ISSUE TITLE
MIDI control behaviour defaults to "Jump to Value"

### ISSUE THREAD

**Issue by ignotus666** [jack-mixer/jack_mixer#124]
Hi, first of all thanks so much for picking up this project again.

I find the "Pick up" function very useful to avoid unwanted sudden changes in volume, but I've found that even if I choose that in the preferences menu and save, when I close and fire Jack Mixer up again, it defaults back to "Jump to value". Would it be possible to make the choice persistent when saved to a config?

BTW, when I have the time I intend to contribute a Spanish translation.

BR

**Comment by SpotlightKid** [comment]
If that is so, it would be a bug. I'll check this later (tomorrow).

Are you sure you have pyxdg installed? otherwise global settings can't be saved.

What version of jack_mixer are you running?

**Comment by ignotus666** [comment]
Yep, I have pyxdg installed. I'm using the latest version (15.1), compiled from git.

**Comment by SpotlightKid** [comment]
Turns out, the midi behaviour setting was correctly saved in mixer project files but not always in the globals settings. Some settings did not trigger writing the global settings when changed, so they were only saved when another setting, which did trigger saving, was changed.

Should be fixed by #125.

**Comment by ignotus666** [comment]
Wow, that was quick! Just tested it and it's working. 

Thank's so much!

**Comment by SpotlightKid** [comment]
I'll probably do a bug fix release on 2021-04-15.
