### ISSUE TITLE
Button size/position issues with monospace bitmap font

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#36]
![image](https://user-images.githubusercontent.com/108225/87210955-61be2b00-c30f-11ea-9b52-64e1e8309673.png)

I'm using https://github.com/mxmilkiib/gohu-ttf

**Comment by SpotlightKid** [comment]
IMHO that's an issue with your GTK theme and out of scope of jack_mixer, which just uses a standard GTK dialog button box layout here.

The alignment of the radio buttons can probably be fixed, though.

**Comment by SpotlightKid** [comment]
Overhauled the dialog layout in #66 and updated a few deprecated Gtk layout widgets used there. This improves the alignment of elements.

The button height and alignment issues with non-proportional fonts are not fixed by this. The buttons are laid out by the `Gtk.Dialog`'s `action_area`, we don't want to mess with this default layout.
