### ISSUE TITLE
Allow to set the client name from UI

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#45]
So as to distinguish "Drum Mix" from "Main Mix".

**Comment by SpotlightKid** [comment]
Do you mean the JACK client name? You can set that using the first positional command line argument (might be changed to a command line option in the future).

**Comment by mxmilkiib** [comment]
Yes. Could that be settable in the main interface? NSM apps cannot do arguments (without nsm-proxy).

**Comment by SpotlightKid** [comment]
Stupid NSM.

**Comment by dsheeler** [comment]
I think NSM dictates the jack client name, as well...

**Comment by SpotlightKid** [comment]
Unfortunately changing the client name at run-time when running as an NSM client is not possible due to the way the client name is used by the session manager to identify the client in the session file.

See also: https://github.com/linuxaudio/new-session-manager/issues/35

It would be possible to set the `pretty-name` JACK meta data on the client. See ##55 for JACK meta data support.
